# Generated by Django 5.2.7 on 2025-10-03 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='conteudo_md',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='registros.categoria'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='registros', to='registros.tag'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='registros.registro')),
            ],
        ),
    ]
