# Generated by Django 5.2.7 on 2025-10-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_conteudo_md_registro_conteudo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#0d6efd', help_text='Cor em formato HEX, ex: #0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text='Nome do ícone da biblioteca react-icons', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo',
            field=models.CharField(blank=True, help_text='Ex: Python, SQL, Bash, Configuração...', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.categoria'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tags',
            field=models.ManyToManyField(blank=True, to='registros.tag'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
