# Generated by Django 5.2.7 on 2025-10-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_categoria_cor_categoria_icone_registro_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cor', models.CharField(default='#6c757d', help_text='Cor em formato HEX', max_length=20)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone', max_length=50, null=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
