# Generated by Django 5.2.7 on 2025-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_registro_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='cor',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='icone',
            field=models.CharField(choices=[('fas fa-code', '🔵 Código'), ('fab fa-python', '🐍 Python'), ('fab fa-js', '🟡 JavaScript'), ('fas fa-database', '🗄️ SQL'), ('fas fa-file-code', '📄 JSON'), ('fab fa-docker', '🐳 Docker'), ('fab fa-linux', '🐧 Linux'), ('fab fa-windows', '🪟 Windows'), ('fas fa-server', '🖥️ Servidor'), ('fas fa-network-wired', '🌐 Rede'), ('fas fa-shield-alt', '🛡️ Segurança'), ('fas fa-cloud', '☁️ Cloud'), ('fas fa-terminal', '💻 Terminal'), ('fas fa-code-branch', '🌿 Git'), ('fas fa-mobile', '📱 Mobile'), ('fas fa-bug', '🐛 Debug'), ('fas fa-rocket', '🚀 Deploy'), ('fas fa-book', '📚 Documentação'), ('fas fa-lightbulb', '💡 Dica'), ('fas fa-exclamation-triangle', '⚠️ Alerta')], default='fas fa-code', max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
